### ISSUE TITLE
Donation page disappeared? Was never there?

### ISSUE THREAD

**Issue by andrewgreenberg** [psas/psas.github.com#1]
Hey! We can't donate via the website right now -- didn't we have a link before? At least a donation page? It's gone, and I can't find evidence of it. Could you dig it up, or make a quick one with the right link? Thank you!

**Comment by andrewgreenberg** [comment]
Whoops, right, you can onlhy have one person own this. Monitoring. Thanks!

**Comment by natronics** [comment]
We had a link to the foundation donation page for PSAS. Where do you want the link to appear in the new site?

**Comment by andrewgreenberg** [comment]
Hmm. The very subtle, hard to find donate link on the front page currently links to http://psas.pdx.edu/sponsor/#donate.

How about a more obnoxious link ("Donate" button?) direct link right to the PSU Foundation page? That seems best...

**Comment by natronics** [comment]
Big links on front, about, and join pages now. Better? Feel free to copy and paste that style markdown link anywhere you think it would work better.

**Comment by andrewgreenberg** [comment]
Totally better. Thanks Nathan!
